{% set version = "0.4.12" %}

package:
  name: html5-parser
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/html5-parser/html5-parser-{{ version }}.tar.gz
  sha256: 3d7f89841aa48b976311f43863178c34c141abcf1dd45b67a7339e61cffe5306
  patches:
    - 0000-no-build-test.diff

build:
  number: 1
  # segfault
  skip: true  # [win and py<310]
  skip: true  # [python_impl == 'pypy']

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - pkg-config  # [unix]
    - m2-pkg-config  # [win]
  host:
    - libxml2
    - pip
    - python
  run:
    - chardet
    - lxml >=3.8.0
    - python

test:
  source_files:
    - test
  imports:
    - html5_parser
  requires:
    - beautifulsoup4
    - coverage
    - pip
    - pytest

about:
  home: https://html5-parser.readthedocs.io
  summary: Fast C based HTML 5 parsing for python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
